### ISSUE TITLE
Question: Configure imported sensor

### ISSUE THREAD

**Issue by hajo62** [FreshlyBrewedCode/hacs-homee#11]
How would I configure how a sensor get's imported.
I.e. my Fibaro wall plug is shown like this. 
Entity state attributes:
```
current_power_w: 0
today_energy_kwh: 1.94
homee_data:
  id: 11
  name: FIBARFO Wall Plug
  profile: 13
  attributes:
    - id: 100
      type: 1
    - id: 101
      type: 44
    - id: 102
      type: 45
    - id: 103
      type: 4
    - id: 104
      type: 47
    - id: 105
      type: 48
    - id: 106
      type: 3
    - id: 107
      type: 347
friendly_name: FIBARFO Wall Plug
```

file core.entity_register:
 ```
               "entity_id": "switch.fibaro_wall_plug",
                "config_entry_id": "7cc80fde59fca178fd33364",
                "device_id": null,
                "area_id": null,
                "unique_id": "11-switch-100",
                "platform": "homee",
                "name": "Fibaro Wall Plug",
                "icon": null,
                "disabled_by": null,
                "capabilities": {},
                "supported_features": 0,
                "device_class": "outlet",
                "unit_of_measurement": null,
                "original_name": "FIBARO Wall Plug",
                "original_icon": null,
                "entity_category": null
```

I would like to i.e. the `unit_of_measurement: kWh` (uppercase W) and maybe set the `state_class: total_increasing`.
I would hope, that this device than is available to the new energy dashboard.
